package com.aicademy.backend.AiManager.Controller;

import com.aicademy.backend.AiManager.DTO.*;
import com.aicademy.backend.AiManager.Service.AiService;
import com.aicademy.backend.AiManager.Service.ImageToTextService;
import com.aicademy.backend.AiManager.Service.VideoSummarizeService;
import com.aicademy.backend.fileManager.DTO.TopicGenerateDTO;
import com.aicademy.backend.fileManager.Service.FileService;
import com.aicademy.backend.fileManager.Service.FirebaseService;
import com.aicademy.backend.fileManager.models.topicEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@RestController
@CrossOrigin
@RequestMapping("/public/bot")
@Tag(name = "AI Controller", description = "AI-powered learning features including chat, image processing, and content generation")
public class AiController {

        @Autowired
        FileService fileService;
        @Autowired
        VideoSummarizeService videoSummarizeService;
        @Autowired
        private AiService aiService;
        @Autowired
        FirebaseService firebaseService;

        /**
         * Handles chat requests by processing the chat history and prompt, generating a
         * response using the LLM model.
         *
         * The history of the chat and the current prompt are passed in JSON format and
         * mapped to the
         * {@link ChatRequestDTO} object.
         *
         * @param chatRequestDTO A data transfer object that contains the chat history
         *                       and the current prompt.
         * @return A {@link ResponseEntity} containing the chat response generated by
         *         the LLM model.
         */
        @Operation(summary = "AI Chat", description = "Generate AI responses based on chat history and current prompt using OpenAI")
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "200", description = "Successful AI response", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))),
                        @ApiResponse(responseCode = "400", description = "Invalid request data"),
                        @ApiResponse(responseCode = "500", description = "Internal server error")
        })
        @PostMapping("/chat")
        public ResponseEntity<ResponseDTO> chat(
                        @Parameter(description = "Chat request containing history and prompt", required = true) @RequestBody ChatRequestDTO chatRequestDTO) {

                System.out.println(chatRequestDTO.getPrompt());
                String prompt = "This is our chat history " + chatRequestDTO.getHistory() +
                                ". Now response to this prompt: " + chatRequestDTO.getPrompt();

                return ResponseEntity.ok()
                                .body(ResponseDTO.builder().content(
                                                aiService.generate(prompt)).build());
        }

        @Operation(summary = "Generate Quiz", description = "Generate AI-powered quiz questions based on provided text content")
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "200", description = "Quiz generated successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ResponseDTO.class))),
                        @ApiResponse(responseCode = "400", description = "Invalid quiz data"),
                        @ApiResponse(responseCode = "500", description = "Internal server error")
        })
        @PostMapping("/quiz")
        public ResponseEntity<ResponseDTO> quiz(
                        @Parameter(description = "Quiz generation data including text, number of questions, and difficulty level", required = true) @RequestBody QuizDataDTO data) {
                System.out.println("Quiz generation API Called");
                return ResponseEntity.ok().body(ResponseDTO.builder()
                                .content(aiService.generateQuiz(data.getText(), data.getTotalQuestions(),
                                                data.getLevel()))
                                .build());
        }

        @Operation(summary = "Generate Image", description = "Generate images using OpenAI DALL-E based on text prompts")
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "200", description = "Image generated and uploaded successfully"),
                        @ApiResponse(responseCode = "400", description = "Invalid image generation request"),
                        @ApiResponse(responseCode = "500", description = "Internal server error")
        })
        @PostMapping("/image/generate")
        public ResponseEntity<?> generateImageUsingOpenAI(
                        @Parameter(description = "Image generation prompt", required = true) @RequestBody ImageGenerateDTO imageGenerateDTO)
                        throws Exception {
                System.out.println("Image generation api called");

                String Url = aiService.generateImage(imageGenerateDTO.getPrompt(), 1, "1024x1024");
                System.out.println(Url);

                String imageName = "generated-image-"
                                + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss")) + ".jpg";

                System.out.println("Image Generated Successfully " + imageName);
                String fireBaseUrl = firebaseService.uploadFileToFirebase(aiService.downloadImage(Url, imageName),
                                imageName);
                System.out.println("file Uploaded to firebase Successfully");
                firebaseService.addFilePathToUser(
                                imageGenerateDTO.getEmail(),
                                imageGenerateDTO.getSubject(),
                                imageGenerateDTO.getTopic(), imageName, fireBaseUrl, true);
                System.out.println("Image path added to user successfully");

                return ResponseEntity.ok()
                                .body(ImageGenResponseDTO.builder().link(fireBaseUrl).build());
        }

        @Operation(summary = "Generate Learning Topic", description = "Generate detailed lesson content for a specific topic and subject using AI")
        @ApiResponses(value = {
                        @ApiResponse(responseCode = "200", description = "Topic generated successfully"),
                        @ApiResponse(responseCode = "400", description = "Invalid topic data"),
                        @ApiResponse(responseCode = "500", description = "Internal server error")
        })
        @PostMapping("/gemini/topic/new")
        public ResponseEntity<?> generateStory(
                        @Parameter(description = "Topic generation data including subject, topic, level, and instructions", required = true) @RequestBody TopicGenerateDTO topicDTO) {
                System.out.println("generateStory called");

                String prompt = "Create a " + topicDTO.getLevel() + " detailed lesson on " + topicDTO.getTopic()
                                + " in " + topicDTO.getSubject() +
                                ". Give it a title and maintain " + topicDTO.getLevel() + " level knowledge." +
                                " Provide some relevant examples and youtube video links. You should Generate minimum 1000 tokens"
                                +
                                " Provide the response in a jsx element to put it in react" +
                                " with tailwind CSS class. background color and text color: bg-gray-950 text-gray-200" +
                                " only provide contents inside the return. do not include return in your response." +
                                " Use class instead of className in CSS. Give width full.don't include ```jsx in response. Response exactly in this format so that i can directly put it in react:"
                                +
                                "  <div class=\"p-4 bg-gray-100 rounded-md shadow-md\">\n" +
                                "      <h2 class=\"text-2xl font-bold mb-4\">Summary of the Video</h2>\n" +
                                "      <p class=\"mb-2\">In this video, the author demonstrates how to implement user registration, authentication, and authorization in Spring Boot web APIs using JSON Web Token (JWT). The next video will cover role-based authorization. Key steps outlined are as follows:</p>\n"
                                +
                                "      <ul class=\"list-disc list-inside mb-4\">\n" +
                                "        <li>Create a new Spring Boot project using Spring Initializer.</li>\n" +
                                "        <li>Add necessary dependencies including Spring Web, MySQL driver, Spring JPA, Validation, and Spring Security.</li>\n"
                                +
                                "        <li>Implement profile retrieval method that requires authentication using JWT.</li>\n"
                                +
                                "      </ul>\n" +
                                "      <p class=\"mb-2\">The application is thoroughly explained and run using Postman to test the endpoints. The next video will delve into implementing role-based authorization using JWT.</p>\n"
                                +
                                "      <p class=\"text-blue-600\">Watch the next video for role-based authorization by following the link in the description.</p>\n"
                                +
                                "    </div> " + "also " + topicDTO.getInstruction();

                topicEntity topic = new topicEntity(topicDTO.getTopic(), aiService.generate(prompt));

                fileService.addTopic(topic, topicDTO.getEmail(), topicDTO.getSubject());
                return ResponseEntity.ok().body("Successfully generated new topic");
        }

        @PostMapping("/gemini/text/summary")
        public ResponseEntity<?> generateQuiz(@RequestBody ResponseDTO data) {
                System.out.println("generate text Summary called");

                String prompt = "Summarize this text clearly and add additional texts,links or videos to know more. "
                                + data
                                + " Provide the response in a jsx element to put it in react. background color and text color: bg-gray-950 text-gray-300"
                                +
                                "use tailwind css to style the element. Use class instead of className to add css. Response exactly like this so that i can directly put it in react:"
                                +
                                "  <div class=\"p-4 bg-gray-100 rounded-md shadow-md\">\n" +
                                "      <h2 class=\"text-2xl font-bold mb-4\">Summary of the Video</h2>\n" +
                                "      <p class=\"mb-2\">In this video, the author demonstrates how to implement user registration, authentication, and authorization in Spring Boot web APIs using JSON Web Token (JWT). The next video will cover role-based authorization. Key steps outlined are as follows:</p>\n"
                                +
                                "      <ul class=\"list-disc list-inside mb-4\">\n" +
                                "        <li>Create a new Spring Boot project using Spring Initializer.</li>\n" +
                                "        <li>Add necessary dependencies including Spring Web, MySQL driver, Spring JPA, Validation, and Spring Security.</li>\n"
                                +
                                "        <li>Implement profile retrieval method that requires authentication using JWT.</li>\n"
                                +
                                "      </ul>\n" +
                                "      <p class=\"mb-2\">The application is thoroughly explained and run using Postman to test the endpoints. The next video will delve into implementing role-based authorization using JWT.</p>\n"
                                +
                                "      <p class=\"text-blue-600\">Watch the next video for role-based authorization by following the link in the description.</p>\n"
                                +
                                "    </div> Do not include any unnecessary character like ```jsx in the response";

                return ResponseEntity.ok().body(ResponseDTO.builder()
                                .content(aiService.generate(prompt))
                                .build());
        }

        @PostMapping("/youtube/summarize")
        public ResponseEntity<?> test(@RequestBody SummarizeRequestDTO summarizeRequest) throws Exception {
                String CAPTION_FILE_PATH = "captions";
                videoSummarizeService.downloadCaptions(summarizeRequest.getUrl(), CAPTION_FILE_PATH);

                String captions = videoSummarizeService.readCaptionsFromFile(CAPTION_FILE_PATH + ".en.srt");
                System.out.println("Captions:\n" + captions);
                String prompt = "Give me a detailed summary of the following caption of a youtube video and" +
                                " point out the key points of the video. Provide the response in a jsx element to put it in react. background color and text color: bg-gray-950 text-gray-300"
                                +
                                "use tailwind css to style the element. Use class instead of className to add css. Do not add the word '```jsx ' in your response. Response exactly like this so that i can directly use it in react:"
                                +
                                "  <div class=\"p-4 bg-gray-100 rounded-md shadow-md\">\n" +
                                "      <h2 class=\"text-2xl font-bold mb-4\">Summary of the Video</h2>\n" +
                                "      <p class=\"mb-2\">In this video, the author demonstrates how to implement user registration, authentication, and authorization in Spring Boot web APIs using JSON Web Token (JWT). The next video will cover role-based authorization. Key steps outlined are as follows:</p>\n"
                                +
                                "      <ul class=\"list-disc list-inside mb-4\">\n" +
                                "        <li>Create a new Spring Boot project using Spring Initializer.</li>\n" +
                                "        <li>Add necessary dependencies including Spring Web, MySQL driver, Spring JPA, Validation, and Spring Security.</li>\n"
                                +
                                "        <li>Implement profile retrieval method that requires authentication using JWT.</li>\n"
                                +
                                "      </ul>\n" +
                                "      <p class=\"mb-2\">The application is thoroughly explained and run using Postman to test the endpoints. The next video will delve into implementing role-based authorization using JWT.</p>\n"
                                +
                                "      <p class=\"text-blue-600\">Watch the next video for role-based authorization by following the link in the description.</p>\n"
                                +
                                "    </div> : " + captions;

                return ResponseEntity.ok().body(ResponseDTO.builder().content(aiService.generate(prompt)).build());
        }

        // Image to text converter made using google document api
        @Autowired
        ImageToTextService imageToTextService;

        @PostMapping("imageToText/upload")
        public ResponseEntity<ImageToTextResponseDTO> uploadFile(@RequestParam("image") MultipartFile file)
                        throws IOException {

                String text = imageToTextService.extractImage(file);
                System.out.println(text);
                String prompt = "This text is extracted from an image So some part of it might be irregular and non sense."
                                +
                                " Correct the parts where words are missing. Do not add anything extra and do not rephrase it."
                                +
                                " Try to keep it natural. Here is the text: " + text;

                return ResponseEntity.ok().body(
                                ImageToTextResponseDTO.builder().text(aiService.generate(prompt)).build());
        }

}
